### ISSUE TITLE
Update loop counts to take into account rewind and/or loop reduction factors

### ISSUE THREAD

**Issue by pwittich** [cms-tracklet/firmware-hls#106]
As discussed in the L1TK algorithm meeting (see [this indico link](https://indico.cern.ch/event/951587/)) we need to ensure that the loop reduction factors are up to date for the various algorithm 

See this table for the required factors. We need to check if the relevant loops are reduced by the appropriate number. 

| module | rewind? | loop reduction| contact |
| ----- | -----  | ----- | ----- | 
| IR | ? | ? | Sarah | 
| VMR | no | 7 | Mei-Li | 
| TE | no | 7 | Andrew |
| TC | yes | 1 (implied) | Andrew | 
| PR | yes | 1 (impled) | Derek | 
| ME | yes | 0 | Alexx | 
| MC | yes | 1 (implied) | Brent | 

Could the relevant people please check and indicate the status of their module. We can create a single PR to do this, the draft of which is #107.

**Comment by meisonlikesicecream** [comment]
My loop reduction factors are different depending on if we have a disk or layer VMR; the disks always seem to take one clock cycle more. Is it alright to have more than one factor?

**Comment by pwittich** [comment]
I think so, we just have to know how to take it into account. It would be good to understand the source (maybe you do) and figure out if you can get rid of it/make it uniform.

**Comment by bryates** [comment]
The MC has a loop reduction factor of 0.

**Comment by aehart** [comment]
@bryates It looks like you're effectively sacrificing one loop iteration to clearing the output memories here:
https://github.com/cms-tracklet/firmware-hls/blob/master/TrackletAlgorithm/MatchCalculator.h#L794-L804

This is how I came up with the loop reduction of one, because you explicitly cannot write any output on the first iteration. But maybe I'm misunderstanding the code for the MC?

**Comment by bryates** [comment]
@aehart you are probably right. I wasn't sure how to get this number, so @djcranshaw helped me out. Basically, when I open the synthesis report, the trip count section states 108. I suppose if it's trip count - 107, then I do have one extra cycle.

**Comment by aehart** [comment]
@bryates I think we're essentially talking about two different things here. I don't think any loop reduction is needed for the MC HLS because you've successfully added the pipeline rewind option. But this is achieved through an "implied" reduction of one iteration (assuming I'm interpreting the code correctly), which we should account for in the emulation when we study truncation.

I've added a note to the above table to indicate that the loop reduction for the MC (and also the TC) is implied by the logic of the loop body, and doesn't need to be accounted for by explicitly reducing the number of iterations.

**Comment by djcranshaw** [comment]
I updated Projection Router to allow the rewind pragma by sacrificing the first loop iteration as is done in MC and now TC. Hopefully this method continues to generalize. N.B. The resources usage for PR went up a bit, by about 15% for LUTs and 80% for FF (as reported by synthesis), but even after the increase the FF usage is still <0.1% for a single PR

**Comment by sseifeln** [comment]
hi everyone, sorry had to miss the meeting again today. I checked the code in the now extremely late PR for the input router and I wasn't using the rewind pragma. If I add it I can decrease the loop iteration latency by one clock cycle (from 6 to 5 clock cycles) and have an insignificant reduction in the LUT usage ( by 5 LUTs). I don't think I understand what is meant by the loop reduction in the table - so I don't know how to respond there.

**Comment by aehart** [comment]
@sseifeln The rewind option enables continuous loop pipelining, which means that in order to hit our latency requirement, the module just needs its processing loop (the one that the pipeline pragma is applied to) to have a trip count of 108. So if you are able to add the rewind option, then your processing loop should be able to use the default `kMaxProc = 108` constant as the upper bound of the loop.

If the rewind option doesn't work, as is the case with some modules, then we have to reduce the number of iterations such that the total latency of the module is 108 clock cycles. But it sounds like this doesn't apply to the IR.

Since the IR on the master branch is so outdated, I would recommend updating it in a separate PR as soon as you can, making sure to include the rewind option. That should address this issue.

**Comment by sseifeln** [comment]
@aehart  and @pwittich  - thanks! Ok will update the IR in a separate PR with the rewind option then.
