### ISSUE TITLE
Split emData/download.sh

### ISSUE THREAD

**Issue by tomalin** [cms-tracklet/firmware-hls#108]
emData/download.sh should be split into two scripts, one to download the LUT data & one to download to the memory data input/output from each algo step. (Motivation: CMSSW when calling the HLS algos will only need the LUT data).

**Comment by aehart** [comment]
@tomalin I've split the tarball in emData/download.sh into MemPrints.tar.gz (test vectors) and LUTs.tar.gz (lookup tables and other small miscellaneous files). I've also added an option for downloading and unpacking only the latter, which should be what's needed for the emulation.

These changes have been made to the fw_synch branch, but since the synchronization is taking some time to complete, I also opened a PR that applies just these changes to the master branch: #112.
